" vim-plug: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
call plug#begin('~/.vim/plugged')
" Shorthand notation; fetches https://github.com/junegunn/vim-easy-align
Plug 'junegunn/vim-easy-align'
" Any valid git URL is allowed
Plug 'https://github.com/junegunn/vim-github-dashboard.git'
" Multiple Plug commands can be written in a single line using | separators
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'
" On-demand loading
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'tpope/vim-fireplace', { 'for': 'clojure' }
" Using a non-master branch
Plug 'rdnetto/YCM-Generator', { 'branch': 'stable' }
" Using a tagged release; wildcard allowed (requires git 1.9.2 or above)
Plug 'fatih/vim-go', { 'tag': '*' }
" Plugin options
Plug 'nsf/gocode', { 'tag': 'v.20150303', 'rtp': 'vim' }
" Plugin outside ~/.vim/plugged with post-update hook
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }

" My pluging
Plug 'editorconfig/editorconfig-vim'
Plug 'powerline/powerline', {'rtp': 'powerline/bindings/vim/'}
" Initialize plugin system
call plug#end()

" Powerline Setting
set laststatus=2		" Always display the statusline in all windows
set showtabline=2		" Always display the tabline, even if there is only one tab
set noshowmode			" Hide the default mode text (e.g. -- INSERT -- below the statusline)
set encoding=utf-8
set t_Co=256
let g:Powerline_symbols='fancy'


" Personal Setting
syntax on			" 語法上色顯示
set ruler			" 第幾行第幾個字
set number			" 顯示行號
set cursorline			" 顯示目前的游標位置
highlight CursorLine cterm=none ctermbg=Black ctermfg=NONE
set hlsearch			" 設定高亮度顯示搜尋結果
syntax enable

" Key mapping
map <C-b> :NERDTreeToggle<CR>

